name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        name: print
        run: echo "hi"
      
